name: kind-kfctl-test

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    - name: Download KinD
      run: |
        curl -Lo ./kind https://github.com/kubernetes-sigs/kind/releases/download/v0.5.1/kind-Linux-amd64
        chmod +x ./kind
        mv ./kind /usr/local/bin/kind
    - name: Check KinD version
      run: kind version
